DROP TABLE CONTACT IF EXISTS;
CREATE TABLE CONTACT(
  id INT(11) NOT NULL PRIMARY KEY,
  nom VARCHAR(100) NULL,
  prenom VARCHAR(100) NULL,
  email VARCHAR(100) NOT NULL,
  age INT(3) NULL
);
